server:
  port: 8008

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicio1
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers/**
        - id: microservicio2
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/accounts/**
        - id: microservicio3
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/credits/**
        - id: microservicio4
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/transacctions/**
