server:
    port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://dbproyecto01:A7gn3rNEaeEX1AatVGIOnaeV1laXE9WsezX2d3BeLINY1H2AzzeOov5vVxv9OF3Pqtg6s401NAKzMwhaIqG2qA==@dbproyecto01.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@dbproyecto01@
  application:
    name: microservicio1

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    prefer-ip-address: true
