server:
    port: 8084
spring:
    data:
        mongodb:
            database: dbproyecto01
            host: localhost
           

application:
    endpoints:
        url:
            valid_address: http://localhost:8081/api/ 
            
resilience4j.circuitbreaker:
    instances:
        DeleteTransactiosn:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 2s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        UpdateTransactions:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 2s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
